spring:
  application:
    name: zuul-gateway
server:
  port:  ${host.instance.port:9090}
zuul:
  routes:
    product-client:
      url: http://product-client:9494
ribbon:
  eureka:
    enabled: true
  #prefix: /api
eureka:
  client:
    service-url:
      defaultZone:  ${eureka_url:http://eureka-server:8761/eureka/}
