server:
  port: ${host.instance.port:9595}
spring:
  application:
    name: product-service
  data:
    cassandra:
      port: 9042
      keyspace-name: ecommerce
      contact-points: 192.168.0.103
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  ${eureka_url:http://eureka-server:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5
