server:
  port: 9595
spring:
  application:
    name: product-service
  data:
    cassandra:
      port: 9042
      keyspace-name: ecommerce
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
