server:
  port: ${host.instance.port:8761}
spring:
  application:
    name: eureka-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
  instance:
    prefer-ip-address: true
    #waitTimeInMsWhenSyncEmpty: 0
