server:
  port: ${host.instance.port:9494}
spring:
  application:
    name: product-client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone:  ${eureka_url:http:/192.168.0.103:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5
labclient:
  cache-enable: false